name: CI

on:
  push:
    branches:
      - main
      - frontend
  pull_request:
    branches:
      - main
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: List root directory contents
      run: ls -R

    - name: List frontend directory contents
      run: ls -R frontend

    - name: Install dependencies
      run: cd frontend && npm install

    - name: Build project
      run: cd frontend && npm run build

    - name: Run tests
      run: cd frontend && npm test

    - name: Deploy to GitHub Pages
      run: cd frontend && npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
